image: golang:1.17

variables:
  BIN_NAME: veil-api-client-go
  ARTIFACTS_DIR: artifacts
  GO_PROJECT: http://192.168.14.215/dev/veil-api-client-go

stages:
  - build
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - go get -u github.com/golang/dep/cmd/dep
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}

build-veil-api-client-go:
  stage: build
  script:
    - dep ensure
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}

test-veil-api-client-go:
  stage: test
  script:
    - dep ensure
    - go test -v -cover ./...